### ISSUE TITLE
Locale "pt-BR" The first letter is not capitalized

### ISSUE THREAD

**Issue by Tiagofsant** [proateen/thirdofthenight#2]
hello, 

I am using 'dayjs/locale/pt-br' to return the months and years in the datePicker, but the first letter does not stay capitalized. It appears like this: "junho 2023" instead of "Junho 2023", as shown in the image below.

![image](https://github.com/proateen/thirdofthenight/assets/79919984/761b8130-be24-4883-9427-afe051c3c861)

**Comment by proateen** [comment]
I think you are looking for [this](https://github.com/iamkun/dayjs)

I didn't make dayjs

**Comment by Tiagofsant** [comment]
thank you!
