### ISSUE TITLE
Auto detect Feature

### ISSUE THREAD

**Issue by fawazahmed0** [proateen/thirdofthenight#4]
Hi, you can add auto detect code from [here](https://github.com/fawazahmed0/last-third-night-calculator/blob/main/code/script.js) , here is a [live demo of auto detect](https://fawazahmed0.github.io/last-third-night-calculator/)

**Comment by proateen** [comment]
Sorry this is without auto-detect intentionally. I assume user input is more accurate than whatever auto-detect is out there. Plus I don't want the burden of giving out false timings
